apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: abinbabu2001/newproject
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets
